//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSys.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public EmployeeType()
        {
            this.Questions = new HashSet<Questions>();
        }
    
        public int ID { get; set; }
        public string EType { get; set; }
        public string ETypeName { get; set; }
    
        public virtual ICollection<Questions> Questions { get; set; }
    }
}
