//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamSys.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Answer { get; set; }
        public int EmployeeTypeID { get; set; }
        public int SubjectTypeID { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual SubjectType SubjectType { get; set; }
    }
}
